'''
Created on Oct 22, 2013

An app to collect data from Stack Exchange to see who the happiest programmers are.

Registered Stack Exchange app: http://stackapps.com/apps/oauth/view/2152

@author: Ryan
'''

import urllib2
import simplejson
import zlib
import sys

key = "i45cYLdEkMGDw4Asznw01w(("
client_id = "2152"
client_secret = "OzWnbQ0nD7NtaoOJJsh5oA(("

# This must be manually generated by going to:
# https://stackexchange.com/oauth/dialog?client_id=2152&redirect_uri=https://stackexchange.com/oauth/login_success
# and approving our app. Then copy the access_token from the address bar.
access_token = "SNTWOGnJvWqOoHN2GU0*OQ))"

site = 'stackoverflow'
page = '1'
page_size = '2'
sort_order = 'desc'
sort_value = 'activity'
se_filter = 'withbody'

#print url

def get_search_by_tag_json(tag):
    url = 'https://api.stackexchange.com/2.1/search?key=' + key + '&access_token=' + access_token + '&page=' + page + '&pagesize=' + page_size + '&order=' + sort_order + '&sort=' + sort_value + '&tagged=' + tag + '&site=' + site + '&filter=' + se_filter
    #print url
    
    response = urllib2.urlopen(url)
    response = response.read()
    json_data = zlib.decompress(response, 16 + zlib.MAX_WBITS)
    return simplejson.loads(json_data)
    
if __name__ == '__main__':
    tag = open(sys.argv[1])
    
    java_json = get_search_by_tag_json(tag)
    for question in java_json['items']:
        print question
    