'''
Created on Oct 22, 2013

An app to collect data from Stack Exchange to see who the happiest programmers are.

Registered Stack Exchange app: http://stackapps.com/apps/oauth/view/2152

@author: Ryan
'''

import urllib2
import simplejson
import zlib

key = "i45cYLdEkMGDw4Asznw01w(("
client_id = "2152"
client_secret = "OzWnbQ0nD7NtaoOJJsh5oA(("

# This must be manually generated by going to:
# https://stackexchange.com/oauth/dialog?client_id=2152&redirect_uri=https://stackexchange.com/oauth/login_success
# and approving our app. Then copy the access_token from the address bar.
access_token = "SNTWOGnJvWqOoHN2GU0*OQ))"

url = 'https://api.stackexchange.com/2.1/search?key=' + key + '&access_token=' + access_token + '&page=1&pagesize=1&order=desc&sort=activity&tagged=java&site=stackoverflow&filter=withbody'
#print url

response = urllib2.urlopen(url)
response = response.read()
jsonData = zlib.decompress(response, 16 + zlib.MAX_WBITS)
print simplejson.loads(jsonData)